### ISSUE TITLE
Texture Compression

### ISSUE THREAD

**Issue by Akshay-IndieDev** [TechNawabs/StickMan#1]
We have to deal with more than 200 sprites for producing a single animation. So Is there a way to create a sprite sheet containing all those sprites and also the resultant sprite sheet must be compressed highly, it will be great if the size of a single sprite sheet is 5MB (max.) else the project will lead to **error in texture rendering** and **memory not enough** issue in future :-1: 

**URGENT: Help & suggestions required.**
@AadityaDev

**Comment by AadityaDev** [comment]
Looking for its solution it will take one two days.
We have to find an alternative or correct way for doing this.

**Comment by Akshay-IndieDev** [comment]
One Solution according to me would  be to use **texture atlases** for several sprites that make up a single animation. this approach will produce a single file containing all the sprite and will compress them.

**Comment by Akshay-IndieDev** [comment]
Working on following approaches :
1.We can pack each texture/sprite into a spritesheet.
2.Then, we can create an atlas using that spritesheet which can be updated later on. 

Hopefully this might work flawlessly :+1:
